export class UserInfo {
	firstName:string;
middleName:string;
	lastName:string;
	gender:string;
	fatherName:string;
	userMobile:number
	userAadhar:number
	 userEmail:string;
	 dateOfBirth:Date;
	 AddressLine1:String;
	 AddressLine2:String;
	 Landmark:string
	 state:string
	 city:string;
	 OccupationType:string;
	 sourceOfIncome:string;
	 annualSalary:number
}